name: masamune_location
description: >-
  Library that provides location information / map related functions of Masamune framework.
  Use Google Map.
version: 0.5.1+3
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_location

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Google Map
  google_maps_flutter: ^1.0.6
  # Location
  location: ^3.0.2
  flutter_compass: ^0.4.2+1
  flutter_polyline_points: ^0.2.1
  # Masamune
  masamune_core: ^0.5.0
  masamune_mobile: ^0.5.0
  masamune_flutter: ^0.5.0
  masamune_localize: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.5.0
  
# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_mobile:
#     path: ../masamune_mobile/
#   masamune_localize:
#     path: ../masamune_localize/
#   masamune_flutter:
#     path: ../masamune_flutter/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
